### ISSUE TITLE
Consider installing `uperf` from EPEL

### ISSUE THREAD

**Issue by portante** [arcalot/arcaflow-plugin-uperf#23]
## Please describe what you would like to see in this project

It would be great to see the containerized plugin use `uperf` from the official EPEL builds.

## Please describe your use case

Reduce the problems providing the proper build environment.

## Additional context

n/a

**Comment by dustinblack** [comment]
Can you expand on what problem this change seeks to solve? As of now, we are pulling and building uperf from a Github release tag, and I'm not aware of any issues this causes.

**Comment by portante** [comment]
You need all the requirements to build `uperf` when you could just install the officially released RPM.
